### PR TITLE
Danish keyboard layout

### PR DESCRIPTION
**Pull request by prrrnd**
I accidentally closed #21 and it seems that I am not able to re-open it without a new commit, so here is a new pull request, including the move to <code>src/locales</code>.

### CODE REVIEW

**Comment by Zhouzi** [comment]
Great, thank you @prrrnd! Would you mind translating the demo dialogue into danish? It'd be cool :)

**Comment by prrrnd** [comment]
There you go, @Zhouzi!

**Comment by Zhouzi** [comment]
Thank you for you contribution @prrrnd :+1:

**Comment by andrusieczko** [comment]
@prrrnd: you haven't added it to the README file as a supported language! :)

**Comment by prrrnd** [comment]
Oops! Added in #25 - Thanks @andrusieczko

**Pull request merged**
