### PR TITLE
Add licence

### PR DESCRIPTION
**Pull request by adambutler**
This pull request adds a licence file. As it stands legally TheaterJS is under "No Licence" you can see the restrictions that this imposes [here](http://choosealicense.com/licenses/).

image

### CODE REVIEW

**Comment by Zhouzi** [comment]
Thank you @adambutler for this pull request. I must admit that I'm not a licence specialist and http://choosealicense.com/ is a great resource. Do you know if creating a LICENSE file is a good practice or it is the only legal way to license a project? Including the license in the source file isn't enough? (e.g. commented at the top of the file)

**Comment by adambutler** [comment]
@Zhouzi You can licence it by any way of publishing a licence anywhere public but having a LICENCE file is the common approach.

I guess having the licence at the top of your source file is enough but I wonder if this *only* licences that single file. I don't know the answer to this, perhaps @haacked or @benbalter could answer this?

**Comment by Stephn-R** [comment]
@Zhouzi, if you are big on Open Source, I would recommend using a [GPU GPL v2 License](http://www.gnu.org/licenses/gpl-2.0.html)

This basically states that any further iterations of your project must be credited towards you and remain open source without the users making a profit off of your code.

AKA: Once and Always Free Forever = GPU GPL v2

**Comment by Zhouzi** [comment]
Thank you @Stephn-R, seems like MIT and GPU GPL v2 are the two major licenses for open source project. I'll have a look and see what's more appropriate.

**Pull request merged**
